

OS := $(shell (uname | sed 's/^CYGWIN_NT.*$$/CYGWIN_NT/'))
ifeq ("$(OS)", "CYGWIN_NT")

PLATFORM = WIN32

else

PLATFORM = UNIX


ifeq ("$(OS)","Linux")
SUB_PLATFORM = Linux
else
ifeq ("$(OS)","Darwin")
SUB_PLATFORM = Darwin
else
ifeq ("$(OS)","SunOS")
SUB_PLATFORM = SunOS
else
ifeq ("$(OS)","FreeBSD")
SUB_PLATFORM = FreeBSD
else
SUB_PLATFORM = Unknown
endif
endif
endif
endif

endif
