#
# Makefile for lropt
#

PP = ../../../..

include $(PP)/Makefile.include

OBJS = lreturn$(OBJ_EXT)

CUSTOM_CLEAN = clean_generated

include $(PP)/Makefile.pseudolib

clean_generated: 
	-$(REMOVE) lreturn.c
