#
# Makefile for decNumber (GNU make)
#

PP = ../../../../..

include $(PP)/Makefile.include

OBJS = decContext$(OBJ_EXT) decimal128$(OBJ_EXT) decimal64$(OBJ_EXT) decNumber$(OBJ_EXT)

include $(PP)/Makefile.pseudolib

