#
# Makefile for catalog
#

PP = ../../..

include $(PP)/Makefile.include

OBJS = catalog$(OBJ_EXT) catstore$(OBJ_EXT) catvars$(OBJ_EXT) deserialization$(OBJ_EXT) CatalogXptrHash$(OBJ_EXT) catmem$(OBJ_EXT) catenum$(OBJ_EXT)

include $(PP)/Makefile.ordlib

	

