#
# Makefile for ph (GNU make)
#

PP = ../../..

include $(PP)/Makefile.include

OBJS = pers_free$(OBJ_EXT) pers_heap$(OBJ_EXT) pers_malloc$(OBJ_EXT) \
       pers_realloc$(OBJ_EXT)

include $(PP)/Makefile.pseudolib