#
# Makefile for bufmgr (GNU make)
#

PP = ../../..

include $(PP)/Makefile.include

OBJS = blk_mngmt$(OBJ_EXT) bm_core$(OBJ_EXT) bm_functions$(OBJ_EXT) \
       bm_rcv$(OBJ_EXT)

include $(PP)/Makefile.ordlib