#
# Makefile for FT
#

PP = ../../..

VPATH =  $(PP)/libs/dtsearch/common

include $(PP)/Makefile.include

OBJS = FTsearch$(OBJ_EXT) FTindex$(OBJ_EXT) ft_index_data$(OBJ_EXT)

OBJS_NODEP += dtsviewr$(OBJ_EXT) \
        dstring$(OBJ_EXT) \
        dfile$(OBJ_EXT) \
        dinputstream$(OBJ_EXT) \
        dtsfc$(OBJ_EXT) \
        dtsearch$(OBJ_EXT)

include $(PP)/Makefile.ordlib