PP = ../..


include $(PP)/Makefile.include

all: AdminGuide.pdf
	@echo ===================================================================
	@echo AdminGuide has been done
	@echo ===================================================================


clean:
	-$(REMOVE) *.aux
	-$(REMOVE) *.dvi
	-$(REMOVE) *.log
	-$(REMOVE) *.toc
	-$(REMOVE) *.ps
	-$(REMOVE) *.pdf
