PP = ../../..


include $(PP)/Makefile.include

all: ClientServerProtocol.pdf
	@echo ===================================================================
	@echo ClientServerProtocol has been done
	@echo ===================================================================


clean:
	-$(REMOVE) *.aux
	-$(REMOVE) *.dvi
	-$(REMOVE) *.log
	-$(REMOVE) *.toc
	-$(REMOVE) *.ps
	-$(REMOVE) *.pdf
