#
# Makefile for llmgr (GNU make)
#

PP = ../../..

include $(PP)/Makefile.include

OBJS = lm_globals$(OBJ_EXT) lock_table$(OBJ_EXT) trans_table$(OBJ_EXT) \
       TransCB$(OBJ_EXT)

include $(PP)/Makefile.ordlib