

all: 
	@echo ===================================================================
	@echo Building Documentation
	@echo ===================================================================
	$(MAKE) -C AdminGuide
	$(MAKE) -C ProgGuide
	$(MAKE) -C QuickStart
	@echo ===================================================================
	@echo Documentation has been done
	@echo ===================================================================

clean:
	$(MAKE) -C AdminGuide clean
	$(MAKE) -C ProgGuide clean
	$(MAKE) -C QuickStart clean

