#
# Makefile for crmutils (GNU make)
#

PP = ../../..

include $(PP)/Makefile.include

OBJS = file_utils$(OBJ_EXT) print_utils$(OBJ_EXT) debug_utils$(OBJ_EXT) \
       str_matcher$(OBJ_EXT) node_utils$(OBJ_EXT) namespace_utils$(OBJ_EXT) \
       exec_output$(OBJ_EXT)

include $(PP)/Makefile.ordlib