.TH SE_RC 8 "June 2005" "Sedna" "Sedna Native XML DBMS"

.SH NAME
se_rc \- shows Sedna server status

.SH SYNOPSIS
.B se_rc
[options]

.SH DESCRIPTION
Displays information about running Sedna daemons

.SH OPTIONS
.TP
\fB--help\fR, \fB-help\fR
display help and exit
.TP
\fB-version\fR
display product version and exit

.SH "SEE ALSO"
.BR se_gov (8),
.BR se_sm (8)

