#
# Makefile for mo
#

PP = ../../..

include $(PP)/Makefile.include

OBJS = shifts$(OBJ_EXT) splits$(OBJ_EXT) nodeinsert$(OBJ_EXT) moinsert$(OBJ_EXT) modelete$(OBJ_EXT) microsurgery$(OBJ_EXT) indirection$(OBJ_EXT) indexupdate$(OBJ_EXT) blocks$(OBJ_EXT) text$(OBJ_EXT) modebug$(OBJ_EXT) mocommon$(OBJ_EXT)
# OBJS = micro$(OBJ_EXT) mo_write_utils$(OBJ_EXT)

include $(PP)/Makefile.ordlib
