#
# Makefile for u (GNU make)
#

PP = ../../..

include $(PP)/Makefile.include

OBJS = u$(OBJ_EXT) uhdd$(OBJ_EXT) ummap$(OBJ_EXT) umutex$(OBJ_EXT) \
       upipe$(OBJ_EXT) uprocess$(OBJ_EXT) usecurity$(OBJ_EXT) usem$(OBJ_EXT) \
       ushm$(OBJ_EXT) usocket$(OBJ_EXT) usystem$(OBJ_EXT) uthread$(OBJ_EXT) \
       utime$(OBJ_EXT) uutils$(OBJ_EXT) uevent$(OBJ_EXT) ugnames$(OBJ_EXT)

include $(PP)/Makefile.pseudolib
