#
# Makefile for wu (GNU make)
#

PP = ../../..

include $(PP)/Makefile.include

OBJS = wuaux$(OBJ_EXT) wuclients$(OBJ_EXT) wusnapshots$(OBJ_EXT) wustatetable$(OBJ_EXT) wuversions$(OBJ_EXT) wu$(OBJ_EXT)

include $(PP)/Makefile.ordlib
