#
# Makefile for ast
#

PP = ../../../..

include $(PP)/Makefile.include

OBJS =  ASTType$(OBJ_EXT) ASTUpdDel$(OBJ_EXT) ASTCreateIndex$(OBJ_EXT) ASTDropRole$(OBJ_EXT) \
		ASTQName$(OBJ_EXT) ASTError$(OBJ_EXT) ASTNamespaceDecl$(OBJ_EXT) ASTOption$(OBJ_EXT) ASTDropIndex$(OBJ_EXT) \
		ASTGrantRole$(OBJ_EXT) ASTCreateTrg$(OBJ_EXT) ASTAlterUser$(OBJ_EXT) ASTCommon$(OBJ_EXT) ASTSchemaElemTest$(OBJ_EXT) \
		ASTCastable$(OBJ_EXT) ASTFLWOR$(OBJ_EXT) ASTLet$(OBJ_EXT) ASTPIConst$(OBJ_EXT) ASTTextTest$(OBJ_EXT) ASTModImport$(OBJ_EXT) \
		ASTFunCall$(OBJ_EXT) ASTItemTest$(OBJ_EXT) ASTTreat$(OBJ_EXT) ASTMetaSchemaCol$(OBJ_EXT) ASTOrderModInt$(OBJ_EXT) \
		ASTCharCont$(OBJ_EXT) ASTTypeVar$(OBJ_EXT) ASTUpdReplace$(OBJ_EXT) ASTDocConst$(OBJ_EXT) ASTDefNamespaceDecl$(OBJ_EXT) \
		ASTOrderBy$(OBJ_EXT) ASTModuleDecl$(OBJ_EXT) ASTTextConst$(OBJ_EXT) ASTLoadFile$(OBJ_EXT) ASTDropDoc$(OBJ_EXT) ASTDeclareCopyNsp$(OBJ_EXT) \
		ASTGrantPriv$(OBJ_EXT) ASTCreateRole$(OBJ_EXT) ASTCreateColl$(OBJ_EXT) ASTDocTest$(OBJ_EXT) ASTPiTest$(OBJ_EXT) \
		ASTNsp$(OBJ_EXT) ASTDropMod$(OBJ_EXT) ASTDropUser$(OBJ_EXT) ASTSeq$(OBJ_EXT) ASTMetaDocs$(OBJ_EXT) \
		ASTAttr$(OBJ_EXT) ASTFor$(OBJ_EXT) ASTMainModule$(OBJ_EXT) ASTStep$(OBJ_EXT) ASTLoadModule$(OBJ_EXT) ASTProlog$(OBJ_EXT) \
		ASTDefCollation$(OBJ_EXT) ASTSpaceSeq$(OBJ_EXT) ASTOrderEmpty$(OBJ_EXT) ASTCreateFtIndex$(OBJ_EXT) \
		ASTVarDecl$(OBJ_EXT) ASTUpdRename$(OBJ_EXT) ASTOrdExpr$(OBJ_EXT) ASTRenameColl$(OBJ_EXT) ASTQuantExpr$(OBJ_EXT) \
		ASTDDO$(OBJ_EXT) ASTMetaSchemaDoc$(OBJ_EXT) ASTNameTest$(OBJ_EXT) ASTOrder$(OBJ_EXT) ASTTypeSingle$(OBJ_EXT) ASTTypeSeq$(OBJ_EXT) \
		ASTUpdMove$(OBJ_EXT) ASTOrderMod$(OBJ_EXT) ASTLibModule$(OBJ_EXT) ASTElementTest$(OBJ_EXT) ASTRevokeRole$(OBJ_EXT) \
		ASTDropFtIndex$(OBJ_EXT) ASTInstOf$(OBJ_EXT) ASTDropColl$(OBJ_EXT) ASTCreateUser$(OBJ_EXT) ASTBaseURI$(OBJ_EXT) \
		ASTPi$(OBJ_EXT) ASTLit$(OBJ_EXT) ASTRevokePriv$(OBJ_EXT) ASTSchemaAttrTest$(OBJ_EXT) ASTFuncDecl$(OBJ_EXT) ASTNodeTest$(OBJ_EXT) \
		ASTEmptyTest$(OBJ_EXT) ASTCast$(OBJ_EXT) ASTBop$(OBJ_EXT) ASTVar$(OBJ_EXT) ASTTypeSwitch$(OBJ_EXT) ASTVersionDecl$(OBJ_EXT) \
		ASTExtExpr$(OBJ_EXT) ASTOrderSpec$(OBJ_EXT) ASTPred$(OBJ_EXT) ASTCase$(OBJ_EXT) ASTElemConst$(OBJ_EXT) ASTElem$(OBJ_EXT) \
		ASTCommTest$(OBJ_EXT) ASTPosVar$(OBJ_EXT) ASTXMLComm$(OBJ_EXT) ASTUop$(OBJ_EXT) ASTQuery$(OBJ_EXT) ASTDropTrg$(OBJ_EXT) \
		ASTCreateDoc$(OBJ_EXT) ASTConstDecl$(OBJ_EXT) ASTIf$(OBJ_EXT) ASTAttribTest$(OBJ_EXT) ASTPragma$(OBJ_EXT) \
		ASTBoundSpaceDecl$(OBJ_EXT) ASTUpdInsert$(OBJ_EXT) ASTCommentConst$(OBJ_EXT) ASTMetaCols$(OBJ_EXT) ASTAttrConst$(OBJ_EXT)

include $(PP)/Makefile.pseudolib
