PP = ../..


include $(PP)/Makefile.include

all: QuickStart.pdf
	@echo ===================================================================
	@echo QuickStart has been done
	@echo ===================================================================

clean:
	-$(REMOVE) *.aux
	-$(REMOVE) *.dvi
	-$(REMOVE) *.log
	-$(REMOVE) *.toc
	-$(REMOVE) *.ps
	-$(REMOVE) *.pdf
