#include "XQFunction.h"

namespace sedna
{
    XQFunction xqueryFunctions[] =
    {
        {"", "abs",  1,  1, "!fn!abs", NULL},
        {"", "adjust-dateTime-to-timezone",  1,  2, "!fn!adjust-dateTime-to-timezone", NULL},
        {"", "adjust-date-to-timezone",  1,  2, "!fn!adjust-date-to-timezone", NULL},
        {"", "adjust-time-to-timezone",  1,  2, "!fn!adjust-time-to-timezone", NULL},
        {"", "avg",  1,  1, "!fn!avg", NULL},
        {"", "base-uri",  0,  1, "!fn!base-uri", NULL},
        {"", "boolean",  1,  1, "!fn!boolean", NULL},
        {"", "ceiling",  1,  1, "!fn!ceiling", NULL},
        {"", "codepoint-equal",  2,  2, "!fn!codepoint-equal", NULL},
        {"", "codepoints-to-string",  1,  1, "!fn!codepoints-to-string", NULL},
        {"", "collection",  1,  1, "!fn!collection", NULL},
        {"", "compare",  2,  3, "!fn!compare", NULL},
        {"", "concat",  2,  UINT32_MAX, "!fn!concat", NULL},
        {"", "contains",  2,  3, "!fn!contains", NULL},
        {"", "count",  1,  1, "!fn!count", NULL},
        {"", "current-date",  0,  0, "!fn!current-date", NULL},
        {"", "current-dateTime",  0,  0, "!fn!current-dateTime", NULL},
        {"", "current-time",  0,  0, "!fn!current-time", NULL},
        {"", "data",  1,  1, "!fn!data", NULL},
        {"", "dateTime",  2,  2, "!fn!dateTime", NULL},
        {"", "day-from-date",  1,  1, "!fn!day-from-date", NULL},
        {"", "day-from-dateTime",  1,  1, "!fn!day-from-dateTime", NULL},
        {"", "days-from-duration",  1,  1, "!fn!days-from-duration", NULL},
        {"", "deep-equal",  2,  3, "!fn!deep-equal", NULL},
        {"", "default-collation",  0,  0, "!fn!default-collation", NULL},
        {"", "distinct-values",  1,  2, "!fn!distinct-values", NULL},
        {"", "doc",  1,  2, "!fn!document", NULL},
        {"", "doc-available",  1,  1, "!fn!doc-available", NULL},
        {"", "document",  1,  2, "!fn!document", NULL},
        {"", "document-uri",  1,  1, "!fn!document-uri", NULL},
        {"", "empty",  1,  1, "!fn!empty", NULL},
        {"", "encode-for-uri",  1,  1, "!fn!encode-for-uri", NULL},
        {"", "ends-with",  2,  3, "!fn!ends-with", NULL},
        {"", "error",  0,  3, "!fn!error", NULL},
        {"", "escape-html-uri",  1,  1, "!fn!escape-html-uri", NULL},
        {"", "exactly-one",  1,  1, "!fn!exactly-one", NULL},
        {"", "exists",  1,  1, "!fn!exists", NULL},
        {"", "false",  0,  0, "!fn!false", NULL},
        {"", "filter_entry_level",  1,  1, "!fn!filter_entry_level", NULL},
        {"", "floor",  1,  1, "!fn!floor", NULL},
        {"", "fthighlight",  2,  3, "!fn!fthighlight", NULL},
        {"", "fthighlight-blocks",  2,  3, "!fn!fthighlight-blocks", NULL},
        {"", "ftindex-scan",  2,  2, "!fn!ftindex-scan", NULL},
        {"", "ftscan",  3,  4, "!fn!ftscan", NULL},
        {"", "ftwindex-scan",  2,  4, "!fn!ftwindex-scan", NULL},
        {"", "hours-from-dateTime",  1,  1, "!fn!hours-from-dateTime", NULL},
        {"", "hours-from-duration",  1,  1, "!fn!hours-from-duration", NULL},
        {"", "hours-from-time",  1,  1, "!fn!hours-from-time", NULL},
        {"", "id",  1,  2, "!fn!id", NULL},
        {"", "idref",  1,  2, "!fn!idref", NULL},
        {"", "implicit-timezone",  0,  0, "!fn!implicit-timezone", NULL},
        {"", "index-of",  2,  3, "!fn!index-of", NULL},
        {"", "index-scan",  3,  3, "!fn!index-scan", NULL},
        {"", "index-scan-between",  4,  4, "!fn!index-scan-between", NULL},
        {"", "in-scope-prefixes",  1,  1, "!fn!in-scope-prefixes", NULL},
        {"", "insert-before",  3,  3, "!fn!insert-before", NULL},
        {"", "iri-to-uri",  1,  1, "!fn!iri-to-uri", NULL},
        {"", "is_ancestor",  2,  2, "!fn!is_ancestor", NULL},
        {"", "item-at",  2,  2, "!fn!item-at", NULL},
        {"", "lang",  1,  2, "!fn!lang", NULL},
        {"", "last",  0,  0, "!fn!last", NULL},
        {"", "local-name",  0,  1, "!fn!local-name", NULL},
        {"", "local-name-from-QName",  1,  1, "!fn!local-name-from-QName", NULL},
        {"", "lower-case",  1,  1, "!fn!lower-case", NULL},
        {"", "matches",  2,  3, "!fn!matches", NULL},
        {"", "max",  1,  2, "!fn!max", NULL},
        {"", "min",  1,  2, "!fn!min", NULL},
        {"", "minutes-from-dateTime",  1,  1, "!fn!minutes-from-dateTime", NULL},
        {"", "minutes-from-duration",  1,  1, "!fn!minutes-from-duration", NULL},
        {"", "minutes-from-time",  1,  1, "!fn!minutes-from-time", NULL},
        {"", "month-from-date",  1,  1, "!fn!month-from-date", NULL},
        {"", "month-from-dateTime",  1,  1, "!fn!month-from-dateTime", NULL},
        {"", "months-from-duration",  1,  1, "!fn!months-from-duration", NULL},
        {"", "name",  0,  1, "!fn!name", NULL},
        {"", "namespace-uri",  0,  1, "!fn!namespace-uri", NULL},
        {"", "namespace-uri-for-prefix",  2,  2, "!fn!namespace-uri-for-prefix", NULL},
        {"", "namespace-uri-from-QName",  1,  1, "!fn!namespace-uri-from-QName", NULL},
        {"", "nilled", 1, 1, "!fn!nilled", NULL},
        {"", "node-kind",  1,  1, "!fn!node-kind", NULL},
        {"", "node-name", 1, 1, "!fn!node-name", NULL},
        {"", "normalize-space",  0,  1, "!fn!normalize-space", NULL},
        {"", "normalize-unicode",  1,  2, "!fn!normalize-unicode", NULL},
        {"", "not",  1,  1, "!fn!not", NULL},
        {"", "number",  0,  1, "!fn!number", NULL},
        {"", "one-or-more",  1,  1, "!fn!one-or-more", NULL},
        {"", "position",  0,  0, "!fn!position", NULL},
        {"", "prefix-from-QName",  1,  1, "!fn!prefix-from-QName", NULL},
        {"", "QName",  2,  2, "!fn!QName", NULL},
        {"", "remove",  2,  2, "!fn!remove", NULL},
        {"", "replace",  3,  4, "!fn!replace", NULL},
        {"", "resolve-QName",  2,  2, "!fn!resolve-QName", NULL},
        {"", "resolve-uri",  1,  2, "!fn!resolve-uri", NULL},
        {"", "reverse",  1,  1, "!fn!reverse", NULL},
        {"", "root",  0,  1, "!fn!root", NULL},
        {"", "round",  1,  1, "!fn!round", NULL},
        {"", "round-half-to-even",  1,  2, "!fn!round-half-to-even", NULL},
        {"", "seconds-from-dateTime",  1,  1, "!fn!seconds-from-dateTime", NULL},
        {"", "seconds-from-duration",  1,  1, "!fn!seconds-from-duration", NULL},
        {"", "seconds-from-time",  1,  1, "!fn!seconds-from-time", NULL},
        {"", "starts-with",  2,  3, "!fn!starts-with", NULL},
        {"", "static-base-uri",  0,  0, "!fn!static-base-uri", NULL},
        {"", "string",  0,  1, "!fn!string", NULL},
        {"", "string-join",  2,  2, "!fn!string-join", NULL},
        {"", "string-length",  0,  1, "!fn!string-length", NULL},
        {"", "string-to-codepoints",  1,  1, "!fn!string-to-codepoints", NULL},
        {"", "string-value",  1,  1, "!fn!string-value", NULL},
        {"", "subsequence",  2,  3, "!fn!subsequence", NULL},
        {"", "substring",  2,  3, "!fn!substring", NULL},
        {"", "substring-after",  2,  3, "!fn!substring-after", NULL},
        {"", "substring-before",  2,  3, "!fn!substring-before", NULL},
        {"", "sum",  1,  2, "!fn!sum", NULL},
        {"", "test",  0,  UINT32_MAX, "!fn!test", NULL},
        {"", "timezone-from-date",  1,  1, "!fn!timezone-from-date", NULL},
        {"", "timezone-from-dateTime",  1,  1, "!fn!timezone-from-dateTime", NULL},
        {"", "timezone-from-time",  1,  1, "!fn!timezone-from-time", NULL},
        {"", "tokenize",  2,  3, "!fn!tokenize", NULL},
        {"", "trace",  2,  2, "!fn!trace", NULL},
        {"", "translate",  3,  3, "!fn!translate", NULL},
        {"", "true",  0,  0, "!fn!true", NULL},
        {"", "typed-value",  1,  1, "!fn!typed-value", NULL},
        {"", "unordered",  1,  1, "!fn!unordered", NULL},
        {"", "upper-case",  1,  1, "!fn!upper-case", NULL},
        {"", "year-from-date",  1,  1, "!fn!year-from-date", NULL},
        {"", "year-from-dateTime",  1,  1, "!fn!year-from-dateTime", NULL},
        {"", "years-from-duration",  1,  1, "!fn!years-from-duration", NULL},
        {"", "zero-or-one",  1,  1, "!fn!zero-or-one", NULL},
        {"", "", 0, 0, "", NULL}
    };

    XQFunction sqlFunctions[] =
    {
        {"", "close",  1,  1, "!fn!sql-close", NULL},
        {"", "commit",  1,  1, "!fn!sql-commit", NULL},
        {"", "connect",  1,  4, "!fn!sql-connect", NULL},
        {"", "exec-update",  2,  UINT32_MAX, "!fn!sql-exec-update", NULL},
        {"", "execute",  2,  UINT32_MAX, "!fn!sql-execute", NULL},
        {"", "prepare",  2,  3, "!fn!sql-prepare", NULL},
        {"", "rollback",  1,  1, "!fn!sql-rollback", NULL},
        {"", "", 0, 0, "", NULL}
    };

    XQFunction seFunctions[] =
    {
        {"", "checkpoint",  0,  0, "!se!checkpoint", NULL},
        {"", "get-property",  1,  1, "!se!get-property", NULL},
        {"", "", 0, 0, "", NULL}
    };
}
