#include "XQFunction.h"

namespace sedna
{
    XQFunction xqueryFunctions[] =
    {
        {"", "abs",  1,  1, 0xFF, "!fn!abs", false, NULL},
        {"", "adjust-dateTime-to-timezone",  1,  2, 0xFF, "!fn!adjust-dateTime-to-timezone", false, NULL},
        {"", "adjust-date-to-timezone",  1,  2, 0xFF, "!fn!adjust-date-to-timezone", false, NULL},
        {"", "adjust-time-to-timezone",  1,  2, 0xFF, "!fn!adjust-time-to-timezone", false, NULL},
        {"", "avg",  1,  1, 0xFF, "!fn!avg", false, NULL},
        {"", "base-uri",  0,  1, 0xFF, "!fn!base-uri", false, NULL},
        {"", "boolean",  1,  1, 0xFF, "!fn!boolean", false, NULL},
        {"", "ceiling",  1,  1, 0xFF, "!fn!ceiling", false, NULL},
        {"", "codepoint-equal",  2,  2, 0xFF, "!fn!codepoint-equal", false, NULL},
        {"", "codepoints-to-string",  1,  1, 0xFF, "!fn!codepoints-to-string", false, NULL},
        {"", "collection",  1,  1, 0xFF, "!fn!collection", false, NULL},
        {"", "compare",  2,  3, 0xFF, "!fn!compare", false, NULL},
        {"", "concat",  2,  UINT32_MAX, 0xFF, "!fn!concat", false, NULL},
        {"", "contains",  2,  3, 0xFF, "!fn!contains", false, NULL},
        {"", "count",  1,  1, 0xFF, "!fn!count", false, NULL},
        {"", "current-date",  0,  0, 0xFF, "!fn!current-date", false, NULL},
        {"", "current-dateTime",  0,  0, 0xFF, "!fn!current-dateTime", false, NULL},
        {"", "current-time",  0,  0, 0xFF, "!fn!current-time", false, NULL},
        {"", "data",  1,  1, 0xFF, "!fn!data", false, NULL},
        {"", "dateTime",  2,  2, 0xFF, "!fn!dateTime", false, NULL},
        {"", "day-from-date",  1,  1, 0xFF, "!fn!day-from-date", false, NULL},
        {"", "day-from-dateTime",  1,  1, 0xFF, "!fn!day-from-dateTime", false, NULL},
        {"", "days-from-duration",  1,  1, 0xFF, "!fn!days-from-duration", false, NULL},
        {"", "deep-equal",  2,  3, 0xFF, "!fn!deep-equal", false, NULL},
        {"", "default-collation",  0,  0, 0xFF, "!fn!default-collation", false, NULL},
        {"", "distinct-values",  1,  2, 0xFF, "!fn!distinct-values", false, NULL},
        {"", "doc",  1,  2, 0xFF, "!fn!document", false, NULL},
        {"", "doc-available",  1,  1, 0xFF, "!fn!doc-available", false, NULL},
        {"", "document",  1,  2, 0xFF, "!fn!document", false, NULL},
        {"", "document-uri",  1,  1, 0xFF, "!fn!document-uri", false, NULL},
        {"", "empty",  1,  1, 0xFF, "!fn!empty", false, NULL},
        {"", "encode-for-uri",  1,  1, 0xFF, "!fn!encode-for-uri", false, NULL},
        {"", "ends-with",  2,  3, 0xFF, "!fn!ends-with", false, NULL},
        {"", "error",  0,  3, 0xFF, "!fn!error", false, NULL},
        {"", "escape-html-uri",  1,  1, 0xFF, "!fn!escape-html-uri", false, NULL},
        {"", "exactly-one",  1,  1, 0xFF, "!fn!exactly-one", false, NULL},
        {"", "exists",  1,  1, 0xFF, "!fn!exists", false, NULL},
        {"", "false",  0,  0, 0xFF, "!fn!false", false, NULL},
        {"", "filter_entry_level",  1,  1, 0xFF, "!fn!filter_entry_level", false, NULL},
        {"", "floor",  1,  1, 0xFF, "!fn!floor", false, NULL},
        {"", "fthighlight",  2,  3, 0xFF, "!fn!fthighlight", false, NULL},
        {"", "fthighlight-blocks",  2,  3, 0xFF, "!fn!fthighlight-blocks", false, NULL},
        {"", "ftindex-scan",  2,  3, 0xFF, "!fn!ftindex-scan", false, NULL},
        {"", "ftscan",  3,  4, 0xFF, "!fn!ftscan", false, NULL},
        {"", "ftwindex-scan",  2,  4, 0xFF, "!fn!ftwindex-scan", false, NULL},
        {"", "hours-from-dateTime",  1,  1, 0xFF, "!fn!hours-from-dateTime", false, NULL},
        {"", "hours-from-duration",  1,  1, 0xFF, "!fn!hours-from-duration", false, NULL},
        {"", "hours-from-time",  1,  1, 0xFF, "!fn!hours-from-time", false, NULL},
        {"", "id",  1,  2, 0xFF, "!fn!id", false, NULL},
        {"", "idref",  1,  2, 0xFF, "!fn!idref", false, NULL},
        {"", "implicit-timezone",  0,  0, 0xFF, "!fn!implicit-timezone", false, NULL},
        {"", "index-of",  2,  3, 0xFF, "!fn!index-of", false, NULL},
        {"", "index-scan",  3,  3, 0xFF, "!fn!index-scan", false, NULL},
        {"", "index-scan-between",  4,  4, 0xFF, "!fn!index-scan-between", false, NULL},
        {"", "in-scope-prefixes",  1,  1, 0xFF, "!fn!in-scope-prefixes", false, NULL},
        {"", "insert-before",  3,  3, 0xFF, "!fn!insert-before", false, NULL},
        {"", "iri-to-uri",  1,  1, 0xFF, "!fn!iri-to-uri", false, NULL},
        {"", "is_ancestor",  2,  2, 0xFF, "!fn!is_ancestor", false, NULL},
        {"", "item-at",  2,  2, 0xFF, "!fn!item-at", false, NULL},
        {"", "lang",  1,  2, 0xFF, "!fn!lang", false, NULL},
        {"", "last",  0,  0, 0xFF, "!fn!last", false, NULL},
        {"", "local-name",  0,  1, 0xFF, "!fn!local-name", false, NULL},
        {"", "local-name-from-QName",  1,  1, 0xFF, "!fn!local-name-from-QName", false, NULL},
        {"", "lower-case",  1,  1, 0xFF, "!fn!lower-case", false, NULL},
        {"", "matches",  2,  3, 0xFF, "!fn!matches", false, NULL},
        {"", "max",  1,  2, 0xFF, "!fn!max", false, NULL},
        {"", "min",  1,  2, 0xFF, "!fn!min", false, NULL},
        {"", "minutes-from-dateTime",  1,  1, 0xFF, "!fn!minutes-from-dateTime", false, NULL},
        {"", "minutes-from-duration",  1,  1, 0xFF, "!fn!minutes-from-duration", false, NULL},
        {"", "minutes-from-time",  1,  1, 0xFF, "!fn!minutes-from-time", false, NULL},
        {"", "month-from-date",  1,  1, 0xFF, "!fn!month-from-date", false, NULL},
        {"", "month-from-dateTime",  1,  1, 0xFF, "!fn!month-from-dateTime", false, NULL},
        {"", "months-from-duration",  1,  1, 0xFF, "!fn!months-from-duration", false, NULL},
        {"", "name",  0,  1, 0xFF, "!fn!name", false, NULL},
        {"", "namespace-uri",  0,  1, 0xFF, "!fn!namespace-uri", false, NULL},
        {"", "namespace-uri-for-prefix",  2,  2, 0xFF, "!fn!namespace-uri-for-prefix", false, NULL},
        {"", "namespace-uri-from-QName",  1,  1, 0xFF, "!fn!namespace-uri-from-QName", false, NULL},
        {"", "nilled", 1, 1, 0xFF, "!fn!nilled", false, NULL},
        {"", "node-kind",  1,  1, 0xFF, "!fn!node-kind", false, NULL},
        {"", "node-name", 1, 1, 0xFF, "!fn!node-name", false, NULL},
        {"", "normalize-space",  0,  1, 0xFF, "!fn!normalize-space", false, NULL},
        {"", "normalize-unicode",  1,  2, 0xFF, "!fn!normalize-unicode", false, NULL},
        {"", "not",  1,  1, 0xFF, "!fn!not", false, NULL},
        {"", "number",  0,  1, 0xFF, "!fn!number", false, NULL},
        {"", "one-or-more",  1,  1, 0xFF, "!fn!one-or-more", false, NULL},
        {"", "position",  0,  0, 0xFF, "!fn!position", false, NULL},
        {"", "prefix-from-QName",  1,  1, 0xFF, "!fn!prefix-from-QName", false, NULL},
        {"", "QName",  2,  2, 0xFF, "!fn!QName", false, NULL},
        {"", "remove",  2,  2, 0xFF, "!fn!remove", false, NULL},
        {"", "replace",  3,  4, 0xFF, "!fn!replace", false, NULL},
        {"", "resolve-QName",  2,  2, 0xFF, "!fn!resolve-QName", false, NULL},
        {"", "resolve-uri",  1,  2, 0xFF, "!fn!resolve-uri", false, NULL},
        {"", "reverse",  1,  1, 0xFF, "!fn!reverse", false, NULL},
        {"", "root",  0,  1, 0xFF, "!fn!root", false, NULL},
        {"", "round",  1,  1, 0xFF, "!fn!round", false, NULL},
        {"", "round-half-to-even",  1,  2, 0xFF, "!fn!round-half-to-even", false, NULL},
        {"", "seconds-from-dateTime",  1,  1, 0xFF, "!fn!seconds-from-dateTime", false, NULL},
        {"", "seconds-from-duration",  1,  1, 0xFF, "!fn!seconds-from-duration", false, NULL},
        {"", "seconds-from-time",  1,  1, 0xFF, "!fn!seconds-from-time", false, NULL},
        {"", "starts-with",  2,  3, 0xFF, "!fn!starts-with", false, NULL},
        {"", "static-base-uri",  0,  0, 0xFF, "!fn!static-base-uri", false, NULL},
        {"", "string",  0,  1, 0xFF, "!fn!string", false, NULL},
        {"", "string-join",  2,  2, 0xFF, "!fn!string-join", false, NULL},
        {"", "string-length",  0,  1, 0xFF, "!fn!string-length", false, NULL},
        {"", "string-to-codepoints",  1,  1, 0xFF, "!fn!string-to-codepoints", false, NULL},
        {"", "string-value",  1,  1, 0xFF, "!fn!string-value", false, NULL},
        {"", "subsequence",  2,  3, 0xFF, "!fn!subsequence", false, NULL},
        {"", "substring",  2,  3, 0xFF, "!fn!substring", false, NULL},
        {"", "substring-after",  2,  3, 0xFF, "!fn!substring-after", false, NULL},
        {"", "substring-before",  2,  3, 0xFF, "!fn!substring-before", false, NULL},
        {"", "sum",  1,  2, 0xFF, "!fn!sum", false, NULL},
        {"", "test",  0,  UINT32_MAX, 0xFF, "!fn!test", false, NULL},
        {"", "timezone-from-date",  1,  1, 0xFF, "!fn!timezone-from-date", false, NULL},
        {"", "timezone-from-dateTime",  1,  1, 0xFF, "!fn!timezone-from-dateTime", false, NULL},
        {"", "timezone-from-time",  1,  1, 0xFF, "!fn!timezone-from-time", false, NULL},
        {"", "tokenize",  2,  3, 0xFF, "!fn!tokenize", false, NULL},
        {"", "trace",  2,  2, 0xFF, "!fn!trace", false, NULL},
        {"", "translate",  3,  3, 0xFF, "!fn!translate", false, NULL},
        {"", "true",  0,  0, 0xFF, "!fn!true", false, NULL},
        {"", "typed-value",  1,  1, 0xFF, "!fn!typed-value", false, NULL},
        {"", "unordered",  1,  1, 0xFF, "!fn!unordered", false, NULL},
        {"", "upper-case",  1,  1, 0xFF, "!fn!upper-case", false, NULL},
        {"", "year-from-date",  1,  1, 0xFF, "!fn!year-from-date", false, NULL},
        {"", "year-from-dateTime",  1,  1, 0xFF, "!fn!year-from-dateTime", false, NULL},
        {"", "years-from-duration",  1,  1, 0xFF, "!fn!years-from-duration", false, NULL},
        {"", "zero-or-one",  1,  1, 0xFF, "!fn!zero-or-one", false, NULL},
        {"", "", 0, 0, 0xFF, "", false, NULL} // dummy record to mark the end
    };

    XQFunction sqlFunctions[] =
    {
        {"", "close",  1,  1, 0xFF, "!fn!sql-close", false, NULL},
        {"", "commit",  1,  1, 0xFF, "!fn!sql-commit", false, NULL},
        {"", "connect",  1,  4, 0xFF, "!fn!sql-connect", false, NULL},
        {"", "exec-update",  2,  UINT32_MAX, 0xFF, "!fn!sql-exec-update", false, NULL},
        {"", "execute",  2,  UINT32_MAX, 0xFF, "!fn!sql-execute", false, NULL},
        {"", "prepare",  2,  3, 0xFF, "!fn!sql-prepare", false, NULL},
        {"", "rollback",  1,  1, 0xFF, "!fn!sql-rollback", false, NULL},
        {"", "", 0, 0, 0xFF, "", false, NULL} // dummy record to mark the end
    };

    XQFunction seFunctions[] =
    {
        {"", "checkpoint",  0,  0, 0xFF, "!se!checkpoint", false, NULL},
        {"", "get-property",  1,  1, 0xFF, "!se!get-property", false, NULL},
        {"", "", 0, 0, 0xFF, "", false, NULL} // dummy record to mark the end
    };
}
