#
# Makefile for updates
#

PP = ../../..

include $(PP)/Makefile.include

OBJS = deletions$(OBJ_EXT) insertions$(OBJ_EXT) updates$(OBJ_EXT) \
       replace$(OBJ_EXT) other_updates$(OBJ_EXT)

include $(PP)/Makefile.ordlib